name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug - List files in the repo to confirm Dockerfile exists
      - name: List files in workspace
        run: ls -al

      # Step 3: Verify Dockerfile exists and print its location
      - name: Check Dockerfile in root
        run: |
          if [ -f ./Dockerfile ]; then
            echo "Dockerfile found in root directory."
          else
            echo "Dockerfile NOT found in root directory!"
          fi

      - name: Check Dockerfile in docker/ directory
        run: |
          if [ -f ./docker/Dockerfile ]; then
            echo "Dockerfile found in docker/ directory."
          else
            echo "Dockerfile NOT found in docker/ directory!"
            exit 1
          fi

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/pharmetrade:1.0 \
            -f ./docker/Dockerfile ./docker \
            --push
