name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug - List files in the repo
      - name: List files in workspace
        run: ls -al

      # Step 3: Check if Dockerfile exists
      - name: Check for Dockerfile
        run: |
          test -f Dockerfile

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/pharmetrade:1.0 \
            -f Dockerfile . \
            --push
