version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # Use the production stage of your multi-stage Dockerfile
      args:               # Pass HTTP/HTTPS proxies if needed
        HTTP_PROXY: ${HTTP_PROXY:-""}  # Set to empty if not defined
        HTTPS_PROXY: ${HTTPS_PROXY:-""}
    ports:
      - "5173:5173"  # Map container port to the host
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-""}  # Set to empty if not defined
      HTTPS_PROXY: ${HTTPS_PROXY:-""}
    command: ["serve", "-s", "dist", "-l", "5173"]
    restart: always  # Ensure the container restarts if it crashes
